name: Server Status Test

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # 4:43 UTC = 9:43 pm PDT = 8:43 pm PST
    # 10:43 UTC = 3:43 am PDT = 2:43 am PST
    # 16:43 UTC = 9:43 am PDT = 8:43 am PST
    # 22:43 UTC = 3:43 pm PDT = 2:43 pm PDT
    # these are requests, scheduled tasks are not guarenteed. They are usually delayed and sometimes skipped (if load is high)
    - cron:  '43 4,10,16,22 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assemble
    - name: Run operational tests with Gradle
      run: ./gradlew testOperational
